name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    paths:
      - flohkiste_dienstplan.py
      - requirements.txt
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed flohkiste_dienstplan.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flohkiste-exe
          path: dist/flohkiste_dienstplan.exe
